#!/bin/sh

[ "$DEBUG" = TRUE ] &&
    echo "\n------------DEBUG MODE------------\n" && python manage.py makemigrations && python manage.py migrate && gunicorn Interapt.wsgi:application --bind 0.0.0.0:8000 --log-level=debug --timeout 180  --workers 4 ||
    echo "\n------------PROD MODE------------\n" && python manage.py migrate && gunicorn habbit.wsgi:application --bind 0.0.0.0:8000 --log-level=debug --timeout 180  --workers 4
