# Generated by Django 3.2.2 on 2021-05-08 06:35

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=255)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('requirements', models.JSONField(default=core.models.get_default_requirements)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('current_end_date', models.DateField()),
                ('location', models.TextField(blank=True, null=True)),
                ('is_color', models.BooleanField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=200)),
                ('role', models.CharField(choices=[('PM', 'Pm'), ('UX', 'Ux'), ('Engr', 'Engr')], max_length=200)),
                ('role_level', models.CharField(blank=True, choices=[('S', 'Senior'), ('M', 'Mid'), ('J', 'Junior')], max_length=200, null=True)),
                ('is_employee', models.BooleanField(default=True)),
                ('skills', models.ManyToManyField(related_name='resources', to='core.Skill')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='ProductResourceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField(null=True)),
                ('positions', models.JSONField(default=core.models.get_default_positions)),
                ('is_employee', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources_through', to='core.product')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_through', to='core.resource')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='resources',
            field=models.ManyToManyField(related_name='products', through='core.ProductResourceInfo', to='core.Resource'),
        ),
    ]
