# Generated by Django 3.2.2 on 2021-05-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='location',
            field=models.CharField(choices=[('AZ', 'Az'), ('IL', 'Il'), ('TX', 'Tx'), ('', 'Empty')], default='', max_length=100),
        ),
    ]
