# Generated by Django 3.2.2 on 2021-05-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_resource_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='current_end_date',
        ),
        migrations.AddField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
