# Generated by Django 3.2.2 on 2021-05-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210508_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productresourceinfo',
            name='start_date',
            field=models.DateField(auto_created=True),
        ),
    ]
